core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("diary.urls")),
    path('admin/', admin.site.urls),
    path("user/", include("user.urls")),
]

diary/urls.py
from django.urls import path

from . import views

app_name = "diary"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("diary/<int:pk>", views.detail, name="detail"),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from . import forms

app_name = "user"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            authentication_form=forms.LoginForm, template_name="user/login.html"
        ),
        name="login",
    ),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout_view, name="logout"),
]

diary/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Diary(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, auto_created=True)
    title = models.CharField(max_length=255)
    diary = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Diaries"

    def __str__(self):
        return self.title

diary/forms.py
from django import forms

from .models import Diary


class CreateDiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = "__all__"
        widgets = {
            "author": forms.Select(
                attrs={
                    "class": "opacity-0 absolute pointer-events-none",
                },
            ),
            "title": forms.TextInput(
                attrs={
                    "class": "border-2 border-gray-700 rounded-md px-2 py-1 w-full xl:w-1/2 lg:w-1/2",
                    "placeholder": "Title",
                },
            ),
            "diary": forms.Textarea(
                attrs={
                    "class": "border-2 border-gray-700 rounded-md px-2 py-1 w-full xl:w-1/2 lg:w-1/2",
                    "placeholder": "Diary",
                },
            ),
        }

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "border border-black px-3 py-2 rounded-md my-2 w-full",
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "border border-black px-3 py-2 rounded-md my-2 w-full",
            }
        )
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "border border-black px-3 py-2 rounded-md my-2 w-full",
            }
        ),
    )

    password2 = forms.CharField(
        label="Repeat password",
        widget=forms.PasswordInput(
            attrs={
                "class": "border border-black px-3 py-2 rounded-md my-2 w-full",
            }
        ),
    )


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "border border-black px-3 py-2 rounded-md my-2 w-full",
            }
        )
    )

    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "border border-black px-3 py-2 rounded-md my-2 w-full",
            }
        ),
    )

diary/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User

from .forms import CreateDiaryForm
from .models import Diary


# Create your views here.
def index(req):
    diaries = Diary.objects.filter(author=req.user).order_by("-created_at")

    return render(req, "diary/index.html", {"diaries": diaries})


def detail(req, pk):
    diary = Diary.objects.get(pk=pk)

    return render(req, "diary/detail.html", {"diary": diary})


def create(req):
    user = User.objects.get(pk=req.user.id)
    form = CreateDiaryForm(initial={"author": user})

    if req.method == "POST":
        form = CreateDiaryForm(req.POST, initial={"author": user})

        if form.is_valid():
            form.save()

            return redirect("/")

    return render(req, "diary/create.html", {"form": form, "user": req.user})

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

from .forms import SignupForm


def signup(req):
    form = SignupForm

    if req.method == "POST":
        form = SignupForm(req.POST)

        if form.is_valid():
            form.save()

            return redirect("../login/")

    return render(req, "user/signup.html", {"form": form})


def logout_view(req):
    logout(req)

    return redirect("/")

diary/templates/diary/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=DM Mono">
    <style>
        body {
            font-family: 'DM Mono', serif;
        }
    </style>

    <script src="https://cdn.tailwindcss.com"></script>

    <title>Create Diary</title>
</head>

<body class="bg-indigo-200">
    <div class="px-5 py-2 bg-white rounded-md mt-16 ml-16 mr-16 xl:mr-32 lg:mr-32 ">
        <div class="text-lg font-semibold mb-5">Create Diary</div>

        <form action="." method="post">
            {% csrf_token %}

            {% for field in form %}
            {% if field.label != "Author" %}
            <div class="">{{ field.label }}</div>
            {% endif %}
            {{ field }}

            <div class="my-2"></div>
            {% endfor %}
            {% if form.errors %}
            <div class="p-2">{{ form.errors }}</div>
            {% endif %}

            <button type="submit"
                class="text-lg bg-teal-400 hover:bg-teal-500 px-4 py-2 rounded-md w-full mt-3">Tambah</button>
        </form>
        <a href="/" type="submit"
            class="text-lg border border-black hover:bg-gray-300 px-4 py-2 rounded-md w-full mt-3 text-center">Batal</a>
    </div>
</body>

</html>

diary/templates/diary/detail.html
{% extends "base.html" %}

{% block title %}
Diary | {{ diary.title }}
{% endblock title %}

{% block content %}
<div class="mx-16 p-6 rounded-md min-h-screen bg-white mb-10 grid content-between">
    <span>
        <div class="mb-2 flex justify-between">
            <span class="font-bold text-2xl">{{ diary.title }}</span>
            <span>{{ diary.created_at }}</span=>
        </div>
        <div class="whitespace-pre-line">{{ diary.diary }}</div>
    </span>

    <div class="place-self-end">
        {{ diary.author }}
    </div>
</div>
{% endblock content %}

diary/templates/diary/index.html
{% extends "base.html" %}

{% block title %}
Diary
{% endblock title %}

{% block content %}
<div class="mx-16 p-6 rounded-md min-h-screen bg-white mb-10">
    <div class="text-2xl font-extrabold">Semua Diary</div>
    <div class="grid grid-cols-3 mt-5 gap-x-3 gap-y-4">
        {% for diary in diaries %}

        <!-- @ Diary Card -->
        <a href="{% url 'diary:detail' diary.id%}"
            class="px-4 py-3 rounded-md shadow-lg bg-amber-300 hover:bg-amber-400 active:bg-amber-500 h-64 grid content-between line-clamp-1">
            <div class="place-self-start self-start">
                <div class="font-bold text-2xl mb-2">{{ diary.title }}</div>
                <p class="line-clamp-6">{{ diary.diary }}</p>
            </div>

            <div class="p-0 m-0 flex justify-between">
                <span class="opacity-60">{{ diary.created_at }}</span>
                <span class="font-semibold">{{ diary.author }}</span>
            </div>
        </a>
        <!--  -->

        {% endfor %}
    </div>
</div>
</div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=DM Mono">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        body {
            font-family: 'DM Mono', serif;
        }
    </style>

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock title %}</title>
</head>

<body class="bg-indigo-200 transition-all">
    <div class="bg-black opacity-0 absolute w-full h-full pointer-events-none" id="backdrop" onclick="closePopup()">
    </div>

    <!-- @ navbar -->
    <nav class="flex justify-between px-16 py-6">
        <a href="/" class="text-2xl font-semibold">Diary</a>

        <!-- @ user authenticated -->
        {% if request.user.is_authenticated %}
        <a href="{% url 'diary:create' %}" class="text-lg bg-cyan-400 hover:bg-cyan-500 px-4 py-2 rounded-md">
            Tambah diary
            <span><i class="fa fa-plus-circle" aria-hidden="true"></i></span>
        </a>

        <!-- @ user not authenticated -->
        {% else %}
        <div class="">
            <a href="{% url 'user:login' %}" class="text-lg hover:bg-gray-400 px-4 py-2 rounded-md">Login</a>
            <a href="{% url 'user:signup' %}"
                class="text-lg bg-teal-400 hover:bg-teal-500 px-4 py-2 rounded-md">Signup</a>
        </div>
        {% endif %}

    </nav>
    <!--  -->

    <div class="absolute px-4 py-3 bg-white left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2 rounded-md opacity-0 pointer-events-none grid justify-items-center w-60"
        id="pop-up">
        <div class="text-lg">Yakin logout?</div>

        <div class="my-4"></div>

        <div class="grid justify-items-center">
            <a href="{% url 'user:logout' %}"
                class="text-lg bg-red-400 hover:bg-red-500 active:bg-red-600 px-10 py-2 rounded-md w-full text-center">Ya</a>

            <div class="my-1"></div>

            <button
                class="text-lg  hover:bg-gray-300 active:bg-gray-400 px-10 py-2 rounded-md w-full text-center border border-gray-500"
                onclick="closePopup()">Batal</button>
        </div>
    </div>

    {% block content %}

    {% endblock content %}

    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

<!-- @ logout button -->
<!-- <button class="text-lg bg-red-400 hover:bg-red-500 active:bg-red-600 px-4 py-2 rounded-md"
            onclick="openPopup()">Logout</button> -->

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>Login</title>
</head>

<body class="bg-gray-200">
    <div
        class="mx-auto mt-20 p-10 rounded-md drop-shadow-2xl grid justify-items-center md:w-2/3 lg:w-1/2 sm:w-4/5 bg-white">
        <div class="text-4xl font-bold mb-10">Login</div>

        <form action="." method="post" class="w-full">
            {% csrf_token %}

            {% for field in  form %}

            <label>{{ field.label }}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>

            {% endfor %}

            <button type="submit"
                class="bg-teal-400 hover:bg-teal-500 active:bg-teal-600 px-5 py-2 mt-3 w-full rounded-md">Login</button>

        </form>

        <div class="my-1"></div>

        <a href="/"
            class=" hover:bg-gray-200 active:bg-gray-300 px-5 py-2 rounded-md text-center border border-black w-full">Batal</a>

    </div>
</body>

</html>

user/templates/user/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>Signup</title>
</head>

<body class="bg-gray-200">
    <div
        class="mx-auto mt-20 p-10 rounded-md drop-shadow-2xl grid justify-items-center md:w-2/3 lg:w-1/2 sm:w-4/5 bg-white">
        <div class="text-4xl font-bold mb-10">Signup</div>

        <form action="." method="post" class="w-full">
            {% csrf_token %}

            {% for field in  form %}

            <label>{{ field.label }}</label>
            <div class="">{{ field }}</div>
            {% if field.errors %}
            <div class="bg-red-400 font-semibold px-3 py-2 rounded-md">{{ field.errors }}</div>
            {% endif %}

            {% endfor %}

            <button type="submit"
                class="bg-teal-400 hover:bg-teal-500 active:bg-teal-600 px-5 py-2 mt-3 w-full rounded-md">Sign
                up</button>

        </form>

        <div class="my-1"></div>

        <a href="/"
            class=" hover:bg-gray-200 active:bg-gray-300 px-5 py-2 rounded-md text-center border border-black w-full">Batal</a>

    </div>
</body>

</html>

<!-- <div class="grid">
    <label for="username">Username</label>
    <input type="text" id="username" class="border border-black px-3 py-2 rounded-md" />
</div>

<div class="my-3"></div>

<div class="grid">
    <label for="password">Password</label>
    <input type="password" id="password" class="border border-black px-3 py-2 rounded-md" />
</div>

<div class="my-3"></div>

<button type="submit"
    class="bg-teal-400 hover:bg-teal-500 active:bg-teal-600 px-5 py-2 w-full rounded-md">Sign up</button> -->